/* Sweety's CA Finals HQ — framework-free vanilla JavaScript */
const STORAGE_KEY="sweety-ca-finals-vanilla-v1";
const seed={progress:{},topicActivity:{},tasks:[{id:1,text:"Solve FR consolidation practice set",subject:"FR",due:"Today",priority:"high",done:false},{id:2,text:"Revise Audit professional ethics",subject:"Audit",due:"Today",priority:"medium",done:false},{id:3,text:"Attempt one IBS case study",subject:"IBS",due:"This week",priority:"low",done:false}],checks:{}};
let state=loadState(),tab="Home",paper="FR",timer=0,timerId=null;
const view=document.querySelector("#view"),title=document.querySelector("#page-title"),subtitle=document.querySelector("#page-subtitle");
const navItems={Home:"⌂","Study Plan":"▤",Tasks:"✓"};
const toolItems={Revision:"↻ Revision overview",Strategy:"◇ CA roadmap & eligibility",Resources:"□ Backup & useful links"};

function freshState(){return JSON.parse(JSON.stringify(seed))}
function loadState(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||freshState()}catch{return freshState()}}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));window.cloudSync?.schedule(state)}
function esc(value=""){return String(value).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
function safeNote(html=""){const doc=new DOMParser().parseFromString(`<div>${html}</div>`,"text/html"),allowed=new Set(["DIV","P","BR","B","STRONG","I","EM","U","MARK","H3","UL","OL","LI","A","SPAN"]);doc.querySelectorAll("*").forEach(el=>{if(el.tagName==="BODY"||el===doc.body.firstElementChild)return;if(!allowed.has(el.tagName)){el.replaceWith(...el.childNodes);return}[...el.attributes].forEach(a=>{if(!(el.tagName==="A"&&a.name==="href")&&!(el.tagName==="SPAN"&&a.name==="data-check"))el.removeAttribute(a.name)});if(el.tagName==="A"&&!/^https?:\/\//i.test(el.getAttribute("href")||""))el.removeAttribute("href")});return doc.body.firstElementChild?.innerHTML||""}
function progressKey(code,index){return `${code}-${index}`}
function allChapters(){return subjects.flatMap(s=>s.chapters.map((chapter,index)=>({s,chapter,index,key:progressKey(s.code,index)})))}
function toast(message){const el=document.createElement("div");el.className="toast";el.textContent=message;document.body.append(el);setTimeout(()=>el.remove(),2500)}
function dateKey(date=new Date()){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`}
function setProgress(key,patch){const previous=state.progress[key]||{};state.topicActivity=state.topicActivity||{};if(Object.prototype.hasOwnProperty.call(patch,"done")&&patch.done!==previous.done){if(patch.done){const day=dateKey();patch.completedAt=day;state.topicActivity[day]=(state.topicActivity[day]||0)+1}else if(previous.completedAt){state.topicActivity[previous.completedAt]=Math.max(0,(state.topicActivity[previous.completedAt]||0)-1);patch.completedAt=""}}state.progress[key]={...previous,...patch};saveState()}
function setupNav(){document.querySelector("#nav").innerHTML=Object.entries(navItems).map(([name,icon])=>`<button class="nav-btn ${name===tab?"active":""}" data-tab="${name}"><span>${icon}</span>${name}</button>`).join("")+`<details class="more-tools" ${toolItems[tab]?"open":""}><summary>More tools</summary>${Object.entries(toolItems).map(([name,label])=>`<button class="tool-link ${name===tab?"active":""}" data-tab="${name}">${label}</button>`).join("")}</details>`;document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render()})}
function render(){if(tab==="Today")tab="Home";if(tab==="Syllabus")tab="Study Plan";setupNav();title.innerHTML=`${tab==="Home"?"Good afternoon, Sweety":tab} <em>✦</em>`;subtitle.textContent=tab==="Home"?"See what matters today, then start studying.":tab==="Study Plan"?"Choose a subject, open a chapter, and record your work.":tab==="Tasks"?"Keep only the next actions you need to finish.":"Helpful tools, kept out of your main workflow.";({Home:renderToday,"Study Plan":renderSyllabus,Revision:renderRevision,Tasks:renderTasks,Strategy:renderStrategy,Resources:renderResources}[tab])();if(tab==="Study Plan")view.insertAdjacentHTML("afterbegin",studyHeatmapHTML());if(tab==="Tasks")view.insertAdjacentHTML("afterbegin",taskCalendarHTML())}

function studyHeatmapHTML(){const cells=[];for(let offset=364;offset>=0;offset--){const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()-offset);const key=dateKey(d),count=state.topicActivity?.[key]||0,level=count===0?0:Math.min(4,count);cells.push(`<i class="heat-cell level-${level}" title="${d.toLocaleDateString()}: ${count} topic${count===1?"":"s"} completed"></i>`)}return `<section class="activity-card"><div class="activity-head"><div><h2>Study consistency</h2><p>Each square is a day. More completed topics create a darker green.</p></div><span>Last 12 months</span></div><div class="heat-scroll"><div class="heatmap">${cells.join("")}</div></div><div class="heat-legend"><span>Less</span>${[0,1,2,3,4].map(n=>`<i class="heat-cell level-${n}"></i>`).join("")}<span>More</span></div></section>`}
function taskCalendarHTML(){const now=new Date(),year=now.getFullYear(),month=now.getMonth(),days=new Date(year,month+1,0).getDate(),start=new Date(year,month,1).getDay(),today=dateKey(),weights={low:1,medium:2,high:3},cells=[];for(let i=0;i<start;i++)cells.push('<i class="calendar-day blank"></i>');for(let day=1;day<=days;day++){const d=new Date(year,month,day),key=dateKey(d),items=(state.tasks||[]).filter(t=>(t.dueDate||(!t.createdAt&&key===today))===key),pending=items.some(t=>!t.done),score=items.filter(t=>t.done).reduce((sum,t)=>sum+(weights[t.priority]||1),0),level=!items.length?0:pending?-1:Math.min(4,Math.ceil(score/2)),label=items.length?`${items.filter(t=>t.done).length}/${items.length} tasks complete`:"No tasks";cells.push(`<i class="calendar-day ${level<0?"missed":`task-level-${level}`} ${key===today?"today":""}" title="${d.toLocaleDateString()}: ${label}">${day}</i>`)}return `<section class="activity-card task-calendar-card"><div class="activity-head"><div><h2>${now.toLocaleString(undefined,{month:"long",year:"numeric"})} task calendar</h2><p>Red means unfinished. Darker green reflects more completed priority points.</p></div><div class="priority-key"><span>Low · 1</span><span>Medium · 2</span><span>High · 3</span></div></div><div class="weekday-row">${["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(x=>`<b>${x}</b>`).join("")}</div><div class="month-grid">${cells.join("")}</div></section>`}

function renderToday(){const all=allChapters(),done=all.filter(x=>state.progress[x.key]?.done).length,pct=Math.round(done/all.length*100);view.innerHTML=`<section class="grid-hero"><article class="mission"><div class="mission-row"><div><span class="kicker">COURSE COMPLETION MISSION</span><h2>Own your complete syllabus.</h2><p>Complete every chapter, then build exam-ready recall through four revision cycles.</p></div><div class="ring" style="--p:${pct}%"><b>${pct}%</b></div></div><div class="stats"><div><small>CHAPTERS MASTERED</small><b>${done} / ${all.length}</b></div><div><small>COMPLETION TARGET</small><b>31 Oct</b></div><div><small>REVISION TARGET</small><b>4 cycles</b></div><div><small>EXAM WINDOW</small><b>2027</b></div></div></article><article class="card deadline"><div class="calendar">31<small>OCT</small></div><div><span class="kicker" style="color:#c77942;background:#fff3ea">NEXT MILESTONE</span><h3>First coverage complete</h3><p>Finish all ${all.length} chapters and first-pass questions.</p><div class="progress"><i style="width:${pct}%;--accent:#dd9964"></i></div><p><b>${done} complete</b> · ${all.length-done} remaining</p></div></article></section><div class="section-title"><div><h2>Your subjects</h2><p>Six papers. One clear path.</p></div><button class="link-btn" id="open-syllabus">View full syllabus →</button></div><section class="subject-grid">${subjects.map(s=>{const count=s.chapters.filter((_,i)=>state.progress[progressKey(s.code,i)]?.done).length,p=Math.round(count/s.chapters.length*100);return `<article class="card subject" data-paper="${s.code}" style="--accent:${s.color}"><span class="code">${s.code}</span><h3>${esc(s.name)}</h3><p>${count} of ${s.chapters.length} chapters mastered</p><div class="progress"><i style="width:${p}%"></i></div><footer><b>${p}%</b><span>Open paper →</span></footer></article>`}).join("")}</section>`;document.querySelector("#open-syllabus").onclick=()=>{tab="Syllabus";render()};document.querySelectorAll("[data-paper]").forEach(el=>el.onclick=()=>{paper=el.dataset.paper;tab="Syllabus";render()})}

function renderSyllabus(){const s=subjects.find(x=>x.code===paper),done=s.chapters.filter((_,i)=>state.progress[progressKey(s.code,i)]?.done).length;view.innerHTML=`<div class="paper-tabs">${subjects.map(x=>`<button data-paper="${x.code}" class="${x.code===paper?"active":""}" style="--accent:${x.color}">${x.code} · ${x.chapters.length}</button>`).join("")}</div><section class="paper-head"><div><h2>${esc(s.name)}</h2><p>ICAI New Scheme · completion and revision tracker</p></div><b>${done}/${s.chapters.length}</b></section><div id="chapters">${s.chapters.map((name,i)=>chapterHTML(s,name,i)).join("")}</div>`;document.querySelectorAll("[data-paper]").forEach(el=>el.onclick=()=>{paper=el.dataset.paper;renderSyllabus()});bindChapters(s)}
function chapterHTML(s,name,i){const key=progressKey(s.code,i),p=state.progress[key]||{},note=p.notesHtml||esc(p.notes||"").replace(/\n/g,"<br>");return `<article class="chapter ${p.done?"done":""}" data-key="${key}" data-index="${i}"><div class="chapter-main"><button class="done-btn">${p.done?"✓":i+1}</button><div class="chapter-name"><b>${esc(name)}</b><small>${p.done?"Mastered":p.revisit?"Flagged to revisit":"Not started"}</small></div><div class="chapter-actions"><button class="flag ${p.revisit?"on":""}">↺ Revisit</button><button class="rev-minus">−</button><strong>${p.revisions||0}</strong><button class="rev-plus">+</button><button class="expand">⌄</button></div></div><div class="chapter-detail"><label class="notes-field">CHAPTER NOTES<div class="rich-editor"><div class="editor-toolbar"><button type="button" data-cmd="bold" title="Bold">B</button><button type="button" data-cmd="italic" title="Italic"><i>I</i></button><button type="button" data-cmd="underline" title="Underline"><u>U</u></button><button type="button" data-block="h3" title="Heading">H</button><button type="button" class="highlight" data-cmd="hiliteColor" data-value="#fff09a" title="Highlight">H</button><button type="button" data-cmd="insertUnorderedList" title="Bullet list">• List</button><button type="button" data-cmd="insertOrderedList" title="Numbered list">1. List</button><button type="button" data-checklist title="Checklist">☐</button><button type="button" data-link title="Add link">🔗</button><button type="button" data-cmd="removeFormat" title="Clear formatting">Tx</button></div><div class="editor-area" contenteditable="true" data-placeholder="Write summaries, formulas, mistakes, mnemonics and revision points…">${safeNote(note)}</div><div class="editor-footer"><button type="button" class="save-note">Save note</button><span class="note-status">${p.noteSavedAt?`Saved ${new Date(p.noteSavedAt).toLocaleDateString()}`:"Ready to write"}</span></div></div></label><label class="side-field">YOUTUBE / LECTURE LINK<input class="youtube" value="${esc(p.youtube||"")}" placeholder="https://youtube.com/…"></label><label class="side-field">STUDY DOCUMENT<span class="file-zone">${p.file?`✓ ${esc(p.file)}`:"＋ Choose PDF, image or document"}<input class="file-input" type="file"></span><span class="file-tools">${p.file?`<button class="file-open">Open</button><button class="file-remove">Remove</button>`:""}</span></label></div></article>`}
function bindChapters(s){document.querySelectorAll(".chapter").forEach(row=>{const key=row.dataset.key,editor=row.querySelector(".editor-area"),noteStatus=row.querySelector(".note-status");row.querySelector(".done-btn").onclick=()=>{setProgress(key,{done:!state.progress[key]?.done});renderSyllabus()};row.querySelector(".flag").onclick=()=>{setProgress(key,{revisit:!state.progress[key]?.revisit});renderSyllabus()};row.querySelector(".rev-minus").onclick=()=>{setProgress(key,{revisions:Math.max(0,(state.progress[key]?.revisions||0)-1)});renderSyllabus()};row.querySelector(".rev-plus").onclick=()=>{setProgress(key,{revisions:(state.progress[key]?.revisions||0)+1});renderSyllabus()};row.querySelector(".expand").onclick=()=>row.classList.toggle("open");editor.oninput=()=>noteStatus.textContent="Unsaved changes";row.querySelectorAll("[data-cmd]").forEach(button=>button.onclick=()=>{editor.focus();document.execCommand(button.dataset.cmd,false,button.dataset.value||null);noteStatus.textContent="Unsaved changes"});row.querySelector("[data-block]").onclick=()=>{editor.focus();document.execCommand("formatBlock",false,"h3");noteStatus.textContent="Unsaved changes"};row.querySelector("[data-checklist]").onclick=()=>{editor.focus();document.execCommand("insertText",false,"☐ ");noteStatus.textContent="Unsaved changes"};row.querySelector("[data-link]").onclick=()=>{const url=prompt("Paste a web link");if(url&&/^https?:\/\//i.test(url)){editor.focus();document.execCommand("createLink",false,url);noteStatus.textContent="Unsaved changes"}};row.querySelector(".save-note").onclick=()=>{const now=new Date().toISOString();setProgress(key,{notesHtml:safeNote(editor.innerHTML),notes:"",noteSavedAt:now});noteStatus.textContent="Saved just now";toast("Note saved and queued for sync")};row.querySelector(".youtube").onchange=e=>setProgress(key,{youtube:e.target.value});row.querySelector(".file-input").onchange=async e=>{const file=e.target.files[0];if(!file)return;if(file.size>50*1024*1024)return alert("Please keep each document below 50 MB.");try{await putDocument(key,file);setProgress(key,{file:file.name});renderSyllabus();toast("Document saved for offline use")}catch{alert("The document could not be saved. Check available browser storage and try again.")}};row.querySelector(".file-open")?.addEventListener("click",async()=>{const d=await getDocument(key);if(!d)return alert("This document is no longer available in this browser.");const url=URL.createObjectURL(d.blob),win=open(url,"_blank");if(!win)alert("Please allow pop-ups to open this document.");setTimeout(()=>URL.revokeObjectURL(url),60000)});row.querySelector(".file-remove")?.addEventListener("click",async()=>{await deleteDocument(key);setProgress(key,{file:""});renderSyllabus()})})}

function renderRevision(){const all=allChapters(),queue=all.filter(x=>state.progress[x.key]?.revisit);view.innerHTML=`<div class="intro"><div><h2>Revision cockpit</h2><p>Active recall, spaced repetition and timed practice.</p></div><span>${queue.length} to revisit</span></div><section class="subject-grid">${[1,2,3,4].map(n=>{const count=all.filter(x=>(state.progress[x.key]?.revisions||0)>=n).length;return `<article class="card"><span class="code">R${n}</span><h3>${["7-day recall","21-day reinforcement","60-day retention","Final exam sprint"][n-1]}</h3><p>${count} / ${all.length} chapters</p><div class="progress"><i style="width:${count/all.length*100}%"></i></div></article>`}).join("")}</section><div class="section-title"><div><h2>Revisit queue</h2><p>Every difficult topic in one place.</p></div></div>${queue.length?queue.map(x=>`<article class="card" style="margin-bottom:7px"><b>${x.s.code} · ${esc(x.chapter)}</b></article>`).join(""):`<div class="card empty">Flag difficult chapters with “Revisit” and they will appear here.</div>`}`}

function renderTasks(){const today=dateKey();view.innerHTML=`<div class="intro"><div><h2>Your tasks</h2><p>Add the task, choose its importance and finish it.</p></div><span>${state.tasks.filter(t=>t.done).length}/${state.tasks.length} done</span></div><form class="task-form task-form-wide"><input id="task-text" required placeholder="What needs to get done?"><select id="task-subject" aria-label="Subject">${subjects.map(s=>`<option>${s.code}</option>`).join("")}</select><select id="task-priority" aria-label="Priority"><option value="low">Low priority</option><option value="medium" selected>Medium priority</option><option value="high">High priority</option></select><input id="task-date" type="date" value="${today}" aria-label="Task date"><button class="primary">Add task</button></form><section class="task-board">${[["Today",t=>!t.done&&(t.dueDate||today)===today],["Upcoming",t=>!t.done&&(t.dueDate||today)!==today],["Done",t=>t.done]].map(([col,filter])=>`<div class="task-col"><h3>${col}</h3>${state.tasks.filter(filter).map(taskHTML).join("")||'<p class="empty-small">Nothing here</p>'}</div>`).join("")}</section>`;document.querySelector(".task-form").onsubmit=e=>{e.preventDefault();const dueDate=document.querySelector("#task-date").value||today;state.tasks.push({id:Date.now(),text:document.querySelector("#task-text").value.trim(),subject:document.querySelector("#task-subject").value,priority:document.querySelector("#task-priority").value,dueDate,createdAt:today,due:dueDate===today?"Today":"Upcoming",done:false});saveState();render()};document.querySelectorAll("[data-task]").forEach(b=>b.onclick=()=>{const t=state.tasks.find(x=>x.id===Number(b.dataset.task));t.done=!t.done;t.completedAt=t.done?today:"";t.priority=t.priority||"low";t.dueDate=t.dueDate||today;saveState();render()})}
function taskHTML(t){const priority=t.priority||"low",due=t.dueDate?new Date(`${t.dueDate}T12:00:00`).toLocaleDateString(undefined,{day:"numeric",month:"short"}):t.due;return `<article class="task priority-${priority}"><button data-task="${t.id}" aria-label="Mark task ${t.done?"incomplete":"complete"}">${t.done?"✓":""}</button><div><b>${esc(t.text)}</b><small>${t.subject} · ${due||"Today"} · <span>${priority} priority</span></small></div></article>`}

function renderStrategy(){const phases=[["NOW → 31 OCT 2026","Complete 100% syllabus","Classes, ICAI modules and first-pass questions."],["NOV–DEC 2026","Revision 1 + question bank","Chapter-wise PYQs, RTPs and a mistake book."],["JAN–MAR 2027","Revision 2 + sectional tests","Timed writing, MCQs and IBS case practice."],["APR–MAY 2027","Revision 3 + full mocks","Strict exam simulation and rapid correction."],["FINAL 30 DAYS","Revision 4 + calm execution","Summary notes, amendments and final mocks."]];view.innerHTML=`<div class="intro"><div><h2>Your 100% preparation roadmap</h2><p>Coverage creates confidence. Revision creates rank.</p></div></div><section class="roadmap">${phases.map((x,i)=>`<article class="card"><span class="step">${i+1}</span><div><small>${x[0]}</small><h3>${x[1]}</h3><p>${x[2]}</p></div></article>`).join("")}</section><div class="section-title"><div><h2>Eligibility & becoming a CA</h2><p>Verify your exact status in ICAI SSP.</p></div></div><section class="qualification">${qualification.map((q,i)=>`<label><input type="checkbox" data-check="${i}" ${state.checks[i]?"checked":""}> ${esc(q)}</label>`).join("")}</section>`;document.querySelectorAll("[data-check]").forEach(c=>c.onchange=()=>{state.checks[c.dataset.check]=c.checked;saveState()})}

const resources=[["ICAI Final syllabus & modules","https://www.icai.org/post/final-nset","Official study material for all six papers"],["BoS Knowledge Portal","https://boslive.icai.org/education_content","Lectures, RTPs, MTPs and suggested answers"],["Digital Learning Campus (SPOM)","https://lms.icai.org/login","Complete applicable Sets A–D"],["ICAI Exam Services","https://eservices.icai.org/","Exam forms and official services"],["ICAI BoS YouTube","https://www.youtube.com/@ICAI_CA_Tube","Official classes and revision sessions"]];
function renderResources(){view.innerHTML=`<section class="backup"><div><span class="kicker">PORTABLE DATA VAULT</span><h2>Take everything with you.</h2><p>The full backup includes progress, revisions, tasks, notes, checks and all uploaded documents.</p></div><div class="backup-actions"><button id="export">↓ Export full backup</button><button class="secondary" id="import">↑ Import & restore</button></div></section><div class="intro"><div><h2>Trusted resource library</h2><p>Official-first. Attempt-specific.</p></div></div><section class="resource-grid">${resources.map(r=>`<a class="card" href="${r[1]}" target="_blank" rel="noreferrer"><h3>${r[0]}</h3><p>${r[2]}</p><small>Open resource ↗</small></a>`).join("")}</section>`;document.querySelector("#export").onclick=exportBackup;document.querySelector("#import").onclick=()=>document.querySelector("#restore-input").click()}

document.querySelector("#focus-btn").onclick=()=>{if(timerId){clearInterval(timerId);timerId=null;document.querySelector("#focus-btn").textContent=`▶ ${formatTimer(timer)}`;return}timerId=setInterval(()=>{timer++;document.querySelector("#focus-btn").textContent=`Ⅱ ${formatTimer(timer)}`},1000)};
function formatTimer(seconds){return `${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`}

const DB_NAME="ca-finals-vanilla-files",STORE="documents";
function openDb(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,1);req.onupgradeneeded=()=>req.result.createObjectStore(STORE);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function putDocument(key,file){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).put({name:file.name,type:file.type,size:file.size,lastModified:file.lastModified||Date.now(),blob:file},key);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}
async function getDocument(key){const db=await openDb();return new Promise((resolve,reject)=>{const req=db.transaction(STORE).objectStore(STORE).get(key);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function deleteDocument(key){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).delete(key);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}
async function listDocuments(){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE),store=tx.objectStore(STORE),keys=store.getAllKeys(),values=store.getAll();tx.oncomplete=()=>resolve(keys.result.map((k,i)=>[k,values.result[i]]));tx.onerror=()=>reject(tx.error)})}
function blobToBase64(blob){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result.split(",")[1]);r.onerror=()=>reject(r.error);r.readAsDataURL(blob)})}
function base64ToBlob(data,type){const raw=atob(data),bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);return new Blob([bytes],{type})}
async function exportBackup(){const docs=await listDocuments(),payload={format:"sweety-ca-finals-hq",version:2,createdAt:new Date().toISOString(),state,documents:await Promise.all(docs.map(async([key,d])=>({key,name:d.name,type:d.type,size:d.size,data:await blobToBase64(d.blob)})))};const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(payload)],{type:"application/json"}));a.download=`sweety-ca-finals-${new Date().toISOString().slice(0,10)}.cafinalbackup`;a.click();URL.revokeObjectURL(a.href);toast("Full backup exported safely")}
document.querySelector("#restore-input").onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const payload=JSON.parse(await file.text());if(payload.format!=="sweety-ca-finals-hq")throw Error("Invalid backup file");if(!confirm("Replace current data with this backup?"))return;state=payload.state||payload.appState;for(const d of payload.documents||[]){const db=await openDb();await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).put({name:d.name,type:d.type,size:d.size,blob:base64ToBlob(d.data,d.type)},d.key);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}saveState();render();toast("Backup restored successfully")}catch(err){alert(err.message||"Could not restore backup")}e.target.value=""};
async function strengthenLocalStorage(){try{if(navigator.storage?.persist)await navigator.storage.persist();const docs=await listDocuments();let changed=false;for(const [key,d] of docs){if(!state.progress[key]?.file){state.progress[key]={...(state.progress[key]||{}),file:d.name};changed=true}}if(changed){saveState();render()}}catch{} }
document.addEventListener("click",event=>{const checklistButton=event.target.closest?.("[data-checklist]");if(checklistButton){event.preventDefault();event.stopImmediatePropagation();const editor=checklistButton.closest(".rich-editor").querySelector(".editor-area");editor.focus();document.execCommand("insertHTML",false,'<span data-check="false" contenteditable="false">☐</span>&nbsp;');checklistButton.closest(".rich-editor").querySelector(".note-status").textContent="Unsaved changes";return}const check=event.target.closest?.(".editor-area [data-check]");if(check){event.preventDefault();check.dataset.check=check.dataset.check!=="true"?"true":"false";check.closest(".rich-editor").querySelector(".note-status").textContent="Unsaved changes"}},true);
document.addEventListener("click",event=>{const paperButton=event.target.closest?.(".paper-tabs [data-paper]");if(!paperButton)return;event.preventDefault();event.stopImmediatePropagation();paper=paperButton.dataset.paper;render()},true);
render();
strengthenLocalStorage();
window.cloudSync?.init({getState:()=>state,applyState:remote=>{const localFiles={};for(const [key,value] of Object.entries(state.progress||{}))if(value.file)localFiles[key]=value.file;state={...freshState(),...remote,progress:{...(remote.progress||{})}};for(const [key,file] of Object.entries(localFiles))state.progress[key]={...(state.progress[key]||{}),file};localStorage.setItem(STORAGE_KEY,JSON.stringify(state));render()}});
