const subjects=[
{code:"FR",name:"Financial Reporting",color:"#8b5cf6",chapters:["Introduction to Indian Accounting Standards","Conceptual Framework for Financial Reporting under Ind AS","Presentation of General Purpose Financial Statements (Ind AS 1, 34 & 7)","Accounting Policies, Events after Reporting & Fair Value (Ind AS 8, 10 & 113)","Assets of Financial Statements (Ind AS 2, 16, 23, 36, 38, 40, 105 & 116)","Liabilities (Ind AS 19 & 37)","Income Taxes & Foreign Exchange (Ind AS 12 & 21)","Disclosures (Ind AS 24, 33 & 108)","Revenue from Contracts with Customers (Ind AS 115)","Other Ind AS (41, 20 & 102)","Financial Instruments (Ind AS 32, 107 & 109)","Business Combinations (Ind AS 103)","Consolidated & Separate Financial Statements (Ind AS 110, 111, 28 & 27)","First-time Adoption of Ind AS (Ind AS 101)","Analysis of Financial Statements","Professional & Ethical Duty of a CA","Accounting and Technology"]},
{code:"AFM",name:"Advanced Financial Management",color:"#10b981",chapters:["Financial Policy and Corporate Strategy","Risk Management","Advanced Capital Budgeting Decisions","Security Analysis","Security Valuation","Portfolio Management","Securitization","Mutual Funds","Derivatives Analysis and Valuation","Foreign Exchange Exposure and Risk Management","International Financial Management","Interest Rate Risk Management","Business Valuation","Mergers, Acquisitions and Corporate Restructuring","Startup Finance"]},
{code:"Audit",name:"Advanced Auditing, Assurance & Professional Ethics",color:"#f59e0b",chapters:["Quality Control","General Auditing Principles and Auditor’s Responsibilities","Audit Planning, Strategy and Execution","Materiality, Risk Assessment and Internal Control","Audit Evidence","Completion and Review","Reporting","Specialised Areas","Related Services","Review of Financial Information","Prospective Financial Information and Other Assurance Services","Digital Auditing & Assurance","Group Audits","Audit of Banks & Non-Banking Financial Companies","Audit of Public Sector Undertakings","Internal Audit","Due Diligence, Investigation & Forensic Accounting","SDG & ESG Assurance","Professional Ethics & Liabilities of Auditors"]},
{code:"DT",name:"Direct Tax Laws & International Taxation",color:"#ef4444",chapters:["Basic Concepts","Incomes which do not form part of Total Income","Profits and Gains of Business or Profession","Capital Gains","Income from Other Sources","Income of Other Persons included in Assessee’s Total Income","Aggregation of Income, Set-off and Carry Forward of Losses","Deductions from Gross Total Income","Assessment of Various Entities","Taxation of Trusts & Institutions","Tax Planning, Tax Avoidance & Tax Evasion","Taxation of Digital Transactions","Deduction, Collection and Recovery of Tax","Income-tax Authorities","Assessment Procedure","Appeals and Revision","Dispute Resolution","Penalties and Prosecution","Miscellaneous Provisions","Tax Audit & Ethical Compliances","Non-resident Taxation","Double Taxation Relief","Transfer Pricing","Advance Rulings","Equalisation Levy & BEPS","Application and Interpretation of Tax Treaties","Overview of Model Tax Conventions" ]},
{code:"IDT",name:"Indirect Tax Laws",color:"#3b82f6",chapters:["Supply under GST","Charge of GST","Place of Supply","Exemptions from GST","Time of Supply","Value of Supply","Input Tax Credit","Registration","Tax Invoice, Credit and Debit Notes","Accounts and Records; E-way Bill","Payment of Tax","Electronic Commerce Transactions","Returns","Import and Export under GST","Refunds","Job Work","Assessment and Audit","Inspection, Search, Seizure and Arrest","Demands and Recovery","Liability to Pay in Certain Cases","Offences, Penalties and Ethical Aspects","Appeals and Revision","Advance Ruling","Miscellaneous GST Provisions","Levy and Exemptions from Customs Duty","Types of Customs Duty","Classification of Goods","Customs Valuation","Importation and Exportation of Goods","Warehousing","Customs Refund","Foreign Trade Policy"]},
{code:"IBS",name:"Integrated Business Solutions",color:"#ec4899",chapters:["Financial Reporting integration","Advanced Financial Management integration","Advanced Auditing & Ethics integration","Direct Tax integration","Indirect Tax integration","Strategic Management integration (SPOM Set B)","Corporate & Economic Laws integration (SPOM Set A)","IBS Case Study Digest — Volume I","IBS Case Study Digest — Volume II","ICAI Students’ Journal case studies","Open-book material indexing","Full 4-hour integrated mock cases"]}
];

const qualification=["Final Course registration is active","Practical training completed by ICAI cut-off","Advanced ICITSS: Advanced IT completed","Advanced ICITSS: MCS completed","Self-Paced Online Module Set A qualified","Self-Paced Online Module Set B qualified","Applicable SPOM Set C qualified","Applicable SPOM Set D qualified","Exam form, photo/signature and fees submitted","Study material checked for July 2027 applicability"];
